name : MrChartman.com
brand : Mr. Chartman
description : MrChartman.com - create chartist chart by pasting spreadsheet
keyword : 
url : http://daigofuji.github.io/mrchartman.com/
email : daigo@daigofujiwara.com
twitter : DaigoFuji
github : DaigoFuji
author : Daigo Fujiwara
analytics : UA-8418273-8
year : 2015
markdown : kramdown
